### ISSUE TITLE
задание 2

### ISSUE THREAD

**Issue by sintsov** [mishkalinda123/First#1]
Нужно сделать страницу на которой:
1.  по центру должен быть заголовок h1
2. под ним две колонки в левой текст, в правой картинка
3. ниже блок с тремя колонками, в каждом по центру должна быть иконка, а под ним текст

**Comment by sintsov** [comment]
Пример 
![image](https://user-images.githubusercontent.com/7813708/78982420-c3ad9f80-7b2a-11ea-8029-c32e1d9c67e6.png)

**Comment by sintsov** [comment]
@mishkalinda123 смотрю твой результат у себя в хроме, вижу вот такое
![image](https://user-images.githubusercontent.com/7813708/82364198-9f8d8a00-9a17-11ea-931f-0b3f57c80223.png)

**Comment by sintsov** [comment]
То есть тут даже на глаз видно, что есть проблемы :)
В целом для целей работы с макетами есть инструмент **pixel perfect** загугли и поставь себе, он тебе еще пригодится.

**Comment by sintsov** [comment]
1. сейчас важная проблема заключается в том, что у тебя контент не имеет контейнера. Поэтому все содержимое растягивается на всю страницу. Это называется резиновая верстка. Сейчас ее редко используют, так как она сильно нарушает внешний вид страницы в зависимости от размера экрана. Поэтому обычно выделяется блок контейнер заданного размера

https://html5book.ru/vyorstka-stranicy-sayta/

давай в рамках следующего PR сделаем так, чтобы весь контент все таки были в контейнере , а не растягивался на весь размер страницы

**Comment by Golenzovskiy** [comment]
Влито в мастер.
